#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "arm-linux-androideabi-gcc -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -march=armv7-a -mandroid -I/home/wangjf/Android/Sdk/android-ndk-r12b-linux-x86_64/android-ndk-r12b//platforms/android-24/arch-arm/usr/include -B/home/wangjf/Android/Sdk/android-ndk-r12b-linux-x86_64/android-ndk-r12b//platforms/android-24/arch-arm/usr/lib -O3 -fomit-frame-pointer -Wall -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -I/usr/local/ssl/android-24/include -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DGHASH_ASM"
  #define PLATFORM "android-armv7"
  #define DATE "Fri Oct 12 14:53:10 CST 2018"
#endif
